export type MediaCategory = 'video' | 'audio' | 'subtitle' | 'thumbnail';

export interface ParsedFormat {
  id: string;
  category: MediaCategory;
  label: string;
  description: string;
  container: string;
  codec?: string;
  bitrate?: number;
  fileSize?: number;
  fileSizeLabel?: string;
  height?: number;
  width?: number;
  fps?: number;
  language?: string;
  languageCode?: string;
  isAutoGenerated?: boolean;
  url?: string;
  itag?: number;
  qualityRank: number;
  hasVideo: boolean;
  hasAudio: boolean;
  isNative: boolean;
  targetExtension?: string;
}

const RESOLUTION_ORDER = [144, 240, 360, 480, 720, 1080, 1440, 2160, 4320];

const AUDIO_OUTPUT_FORMATS = [
  { ext: 'opus', label: 'Opus', mime: 'audio/opus' },
  { ext: 'm4a', label: 'M4A (AAC)', mime: 'audio/mp4' },
  { ext: 'mp3', label: 'MP3', mime: 'audio/mpeg' },
  { ext: 'aac', label: 'AAC', mime: 'audio/aac' },
  { ext: 'flac', label: 'FLAC', mime: 'audio/flac' },
  { ext: 'wav', label: 'WAV', mime: 'audio/wav' },
  { ext: 'ogg', label: 'OGG Vorbis', mime: 'audio/ogg' },
] as const;

export function formatBytes(bytes?: number): string | undefined {
  if (!bytes || bytes <= 0) {
    return undefined;
  }

  const units = ['B', 'KB', 'MB', 'GB'];
  let value = bytes;
  let unitIndex = 0;

  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex += 1;
  }

  return `${value.toFixed(unitIndex === 0 ? 0 : 1)} ${units[unitIndex]}`;
}

export function resolutionLabel(height?: number): string {
  if (!height) {
    return 'Unknown';
  }

  if (height >= 4320) return '8K';
  if (height >= 2160) return '4K';
  if (height >= 1440) return '1440p';
  return `${height}p`;
}

function qualityRank(height?: number, fps?: number): number {
  const heightIndex = height
    ? RESOLUTION_ORDER.indexOf(RESOLUTION_ORDER.find((r) => r >= height) ?? height)
    : -1;
  const fpsBonus = fps && fps > 30 ? 0.5 : 0;
  return (heightIndex >= 0 ? heightIndex : 0) * 10 + fpsBonus;
}

function parseMimeType(mimeType?: string): { container: string; codec?: string } {
  if (!mimeType) {
    return { container: 'unknown' };
  }

  const [typePart, ...params] = mimeType.split(';').map((part) => part.trim());
  const container = typePart.split('/')[1] ?? 'unknown';
  const codecParam = params.find((param) => param.startsWith('codecs='));
  const codec = codecParam?.replace('codecs=', '').replace(/"/g, '');

  return { container, codec };
}

function dedupeKey(format: ParsedFormat): string {
  return [
    format.category,
    format.height ?? 0,
    format.fps ?? 0,
    format.codec ?? '',
    format.container,
    format.hasAudio,
    format.hasVideo,
    format.targetExtension ?? '',
    format.languageCode ?? '',
  ].join('|');
}

export function parseStreamingFormats(
  adaptiveFormats: Array<Record<string, unknown>>,
  progressiveFormats: Array<Record<string, unknown>> = [],
): ParsedFormat[] {
  const parsed: ParsedFormat[] = [];

  for (const format of [...progressiveFormats, ...adaptiveFormats]) {
    const mimeType = String(format['mime_type'] ?? format['mimeType'] ?? '');
    const { container, codec } = parseMimeType(mimeType);
    const height = Number(format['height'] ?? 0) || undefined;
    const width = Number(format['width'] ?? 0) || undefined;
    const fps = Number(format['fps'] ?? 0) || undefined;
    const bitrate = Number(format['bitrate'] ?? format['average_bitrate'] ?? 0) || undefined;
    const fileSize = Number(format['content_length'] ?? format['contentLength'] ?? 0) || undefined;
    const itag = Number(format['itag'] ?? 0) || undefined;
    const url = String(format['url'] ?? '');
    const hasVideo = Boolean(format['has_video'] ?? (mimeType.includes('video') || height));
    const hasAudio = Boolean(format['has_audio'] ?? (mimeType.includes('audio') || format['audio_quality']));

    if (!url || url === 'undefined') {
      continue;
    }

    if (hasVideo && hasAudio) {
      parsed.push({
        id: `video-progressive-${itag}`,
        category: 'video',
        label: `${resolutionLabel(height)}${fps ? ` @ ${fps}fps` : ''}`,
        description: `${codec ?? container.toUpperCase()} · Progressive (video + audio)`,
        container,
        codec,
        bitrate,
        fileSize,
        fileSizeLabel: formatBytes(fileSize),
        height,
        width,
        fps,
        url,
        itag,
        qualityRank: qualityRank(height, fps) + 100,
        hasVideo: true,
        hasAudio: true,
        isNative: true,
      });
      continue;
    }

    if (hasVideo && !hasAudio) {
      parsed.push({
        id: `video-${itag}-${height ?? 'na'}-${fps ?? 'na'}`,
        category: 'video',
        label: `${resolutionLabel(height)}${fps ? ` @ ${fps}fps` : ''}`,
        description: `${codec ?? container.toUpperCase()} · Video only (mux with audio on download)`,
        container,
        codec,
        bitrate,
        fileSize,
        fileSizeLabel: formatBytes(fileSize),
        height,
        width,
        fps,
        url,
        itag,
        qualityRank: qualityRank(height, fps),
        hasVideo: true,
        hasAudio: false,
        isNative: true,
      });
      continue;
    }

    if (hasAudio && !hasVideo) {
      parsed.push({
        id: `audio-native-${itag}`,
        category: 'audio',
        label: `${Math.round((bitrate ?? 0) / 1000) || 'Best'} kbps`,
        description: `${codec ?? container.toUpperCase()} · Native audio stream`,
        container,
        codec,
        bitrate,
        fileSize,
        fileSizeLabel: formatBytes(fileSize),
        url,
        itag,
        qualityRank: Math.round((bitrate ?? 0) / 1000),
        hasVideo: false,
        hasAudio: true,
        isNative: true,
        targetExtension: container === 'mp4' ? 'm4a' : container,
      });
    }
  }

  const bestAudio = [...parsed]
    .filter((format) => format.category === 'audio')
    .sort((a, b) => b.qualityRank - a.qualityRank)[0];

  if (bestAudio) {
    for (const output of AUDIO_OUTPUT_FORMATS) {
      const isNative =
        output.ext === bestAudio.targetExtension || output.ext === bestAudio.container;

      parsed.push({
        id: `audio-convert-${output.ext}-${bestAudio.itag}`,
        category: 'audio',
        label: output.label,
        description: isNative
          ? `${output.label} · Native stream`
          : `${output.label} · Converted from best available audio`,
        container: output.ext,
        codec: output.label,
        fileSize: bestAudio.fileSize,
        fileSizeLabel: bestAudio.fileSizeLabel,
        url: bestAudio.url,
        itag: bestAudio.itag,
        qualityRank: bestAudio.qualityRank + (isNative ? 1000 : 500),
        hasVideo: false,
        hasAudio: true,
        isNative,
        targetExtension: output.ext,
      });
    }
  }

  const unique = new Map<string, ParsedFormat>();
  for (const format of parsed) {
    unique.set(dedupeKey(format), format);
  }

  return [...unique.values()].sort((a, b) => {
    if (a.category !== b.category) {
      const order: Record<MediaCategory, number> = {
        video: 0,
        audio: 1,
        subtitle: 2,
        thumbnail: 3,
      };
      return order[a.category] - order[b.category];
    }

    if (a.category === 'video') {
      return a.qualityRank - b.qualityRank;
    }

    return b.qualityRank - a.qualityRank;
  });
}

export function parseCaptions(
  captionTracks: Array<Record<string, unknown>>,
): ParsedFormat[] {
  return captionTracks.map((track, index) => {
    const languageCode = String(track['language_code'] ?? track['languageCode'] ?? 'und');
    const name = track['name'] as { text?: string } | undefined;
    const language = String(name?.text ?? track['languageName'] ?? languageCode);
    const isAutoGenerated = Boolean(track['kind'] === 'asr' || track['vss_id']?.toString().startsWith('a.'));

    return {
      id: `subtitle-${languageCode}-${index}`,
      category: 'subtitle',
      label: language,
      description: isAutoGenerated ? 'Auto-generated captions' : 'Manual captions',
      container: 'vtt',
      language,
      languageCode,
      isAutoGenerated,
      url: String(track['base_url'] ?? track['baseUrl'] ?? ''),
      qualityRank: index,
      hasVideo: false,
      hasAudio: false,
      isNative: true,
      targetExtension: 'vtt',
    };
  });
}

export function parseThumbnails(
  thumbnails: Array<Record<string, unknown>>,
): ParsedFormat[] {
  const uniqueUrls = new Map<string, ParsedFormat>();

  for (const thumb of thumbnails) {
    const url = String(thumb['url'] ?? '');
    const width = Number(thumb['width'] ?? 0) || undefined;
    const height = Number(thumb['height'] ?? 0) || undefined;

    if (!url) {
      continue;
    }

    const key = `${width ?? 0}x${height ?? 0}`;
    if (uniqueUrls.has(key)) {
      continue;
    }

    uniqueUrls.set(key, {
      id: `thumbnail-${width ?? 'auto'}-${height ?? 'auto'}`,
      category: 'thumbnail',
      label: width && height ? `${width}×${height}` : 'Thumbnail',
      description: 'JPEG thumbnail image',
      container: 'jpg',
      width,
      height,
      url,
      qualityRank: (width ?? 0) * (height ?? 0),
      hasVideo: false,
      hasAudio: false,
      isNative: true,
      targetExtension: 'jpg',
    });
  }

  return [...uniqueUrls.values()].sort((a, b) => a.qualityRank - b.qualityRank);
}

export function extractVideoId(input: string): string | null {
  const trimmed = input.trim();

  if (/^[\w-]{11}$/.test(trimmed)) {
    return trimmed;
  }

  try {
    const url = new URL(trimmed);
    const host = url.hostname.replace('www.', '');

    if (host === 'youtu.be') {
      return url.pathname.slice(1).split('/')[0] || null;
    }

    if (host.includes('youtube.com')) {
      if (url.pathname.startsWith('/watch')) {
        return url.searchParams.get('v');
      }

      if (url.pathname.startsWith('/shorts/')) {
        return url.pathname.split('/')[2] ?? null;
      }

      if (url.pathname.startsWith('/embed/')) {
        return url.pathname.split('/')[2] ?? null;
      }
    }
  } catch {
    return null;
  }

  return null;
}
