export type MediaCategory = 'video' | 'audio' | 'subtitle' | 'thumbnail';
export type DownloadTab = 'video' | 'audio' | 'extras';

export interface DownloadFormat {
  id: string;
  category: MediaCategory;
  label: string;
  description: string;
  container: string;
  codec?: string;
  bitrate?: number;
  fileSize?: number;
  fileSizeLabel?: string;
  height?: number;
  width?: number;
  fps?: number;
  language?: string;
  languageCode?: string;
  isAutoGenerated?: boolean;
  qualityRank: number;
  hasVideo: boolean;
  hasAudio: boolean;
  isNative: boolean;
  targetExtension?: string;
}

export interface FormatRecommendations {
  videoId?: string;
  audioId?: string;
  videoLabel: string;
  audioLabel: string;
}

export interface VideoAnalysis {
  videoId: string;
  title: string;
  author: string;
  duration: number;
  durationLabel: string;
  viewCount?: string;
  description: string;
  thumbnailUrl: string;
  formats: DownloadFormat[];
  maxResolution: number;
  maxResolutionLabel: string;
  recommendations: FormatRecommendations;
}

export interface SelectOption<T = string> {
  label: string;
  value: T;
}

export function resolutionLabel(height: number): string {
  if (height >= 4320) return '8K';
  if (height >= 2160) return '4K';
  if (height >= 1440) return '1440p';
  return `${height}p`;
}

export function formatBitrate(bitrate?: number): string {
  if (!bitrate) {
    return 'Unknown';
  }

  return `${Math.round(bitrate / 1000)} kbps`;
}
