import type { DownloadFormat, SelectOption } from '../models/download.models';
import { formatBitrate, resolutionLabel } from '../models/download.models';

export function getVideoFormats(formats: DownloadFormat[]): DownloadFormat[] {
  return formats.filter((format) => format.category === 'video');
}

export function getAudioFormats(formats: DownloadFormat[]): DownloadFormat[] {
  return formats.filter((format) => format.category === 'audio');
}

export function getSubtitleFormats(formats: DownloadFormat[]): DownloadFormat[] {
  return formats.filter((format) => format.category === 'subtitle');
}

export function getThumbnailFormats(formats: DownloadFormat[]): DownloadFormat[] {
  return formats.filter((format) => format.category === 'thumbnail');
}

export function buildResolutionOptions(formats: DownloadFormat[]): SelectOption<number>[] {
  const heights = [...new Set(getVideoFormats(formats).map((format) => format.height).filter(Boolean))] as number[];
  const maxHeight = heights.length ? Math.max(...heights) : 0;

  return heights
    .sort((a, b) => a - b)
    .map((height) => ({
      label: height === maxHeight ? `${resolutionLabel(height)} · Max available` : resolutionLabel(height),
      value: height,
    }));
}

export function buildFpsOptions(formats: DownloadFormat[], height: number): SelectOption<number>[] {
  const fpsValues = [
    ...new Set(
      getVideoFormats(formats)
        .filter((format) => format.height === height && format.fps)
        .map((format) => Math.round(format.fps as number)),
    ),
  ];

  return fpsValues.sort((a, b) => a - b).map((fps) => ({ label: `${fps} FPS`, value: fps }));
}

export function buildVideoContainerOptions(
  formats: DownloadFormat[],
  height: number,
  fps: number,
): SelectOption<string>[] {
  return getVideoFormats(formats)
    .filter((format) => format.height === height && Math.round(format.fps ?? 30) === fps)
    .map((format) => ({
      label: `${format.container.toUpperCase()}${format.hasAudio ? ' · with audio' : ' · video only'} · ${format.codec ?? 'stream'}`,
      value: format.id,
    }));
}

export function pickDefaultVideoFormat(formats: DownloadFormat[], recommendedId?: string): DownloadFormat | null {
  if (recommendedId) {
    const recommended = formats.find((format) => format.id === recommendedId);
    if (recommended) {
      return recommended;
    }
  }

  return (
    [...getVideoFormats(formats)].sort((a, b) => {
      const combined = (format: DownloadFormat) => (format.hasAudio ? 1_000_000 : 0);
      return combined(b) + b.qualityRank - (combined(a) + a.qualityRank);
    })[0] ?? null
  );
}

export function buildAudioFormatOptions(formats: DownloadFormat[]): SelectOption<string>[] {
  const seen = new Set<string>();

  return getAudioFormats(formats)
    .filter((format) => {
      const key = format.label;
      if (seen.has(key)) {
        return false;
      }

      seen.add(key);
      return true;
    })
    .map((format) => ({
      label: `${format.label}${format.isNative ? '' : ' · converted'}`,
      value: format.id,
    }));
}

export function buildAudioBitrateOptions(formats: DownloadFormat[], formatId: string): SelectOption<string>[] {
  const selected = formats.find((format) => format.id === formatId);
  if (!selected) {
    return [];
  }

  return [
    {
      label: selected.bitrate ? formatBitrate(selected.bitrate) : 'Best available',
      value: formatId,
    },
  ];
}

export function buildSubtitleOptions(formats: DownloadFormat[]): SelectOption<string>[] {
  return getSubtitleFormats(formats).map((format) => ({
    label: `${format.label}${format.isAutoGenerated ? ' · auto' : ''}`,
    value: format.id,
  }));
}

export function buildThumbnailOptions(formats: DownloadFormat[]): SelectOption<string>[] {
  return getThumbnailFormats(formats).map((format) => ({
    label: format.width && format.height ? `${format.width}×${format.height}` : format.label,
    value: format.id,
  }));
}

export function buildSelectionSummary(format: DownloadFormat | null): Array<{ label: string; value: string }> {
  if (!format) {
    return [];
  }

  const rows: Array<{ label: string; value: string }> = [
    { label: 'Type', value: format.category },
    { label: 'Format', value: (format.targetExtension ?? format.container).toUpperCase() },
  ];

  if (format.height) {
    rows.push({ label: 'Resolution', value: resolutionLabel(format.height) });
  }

  if (format.fps) {
    rows.push({ label: 'FPS', value: `${Math.round(format.fps)}` });
  }

  if (format.bitrate) {
    rows.push({ label: 'Bitrate', value: formatBitrate(format.bitrate) });
  }

  if (format.codec) {
    rows.push({ label: 'Codec', value: format.codec });
  }

  if (format.fileSizeLabel) {
    rows.push({ label: 'Est. size', value: format.fileSizeLabel });
  }

  if (format.language) {
    rows.push({ label: 'Language', value: format.language });
  }

  rows.push({ label: 'Source', value: format.isNative ? 'Native stream' : 'Converted on download' });

  return rows;
}
